name: PHPComposer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['5.6', '7.2', '7.3', '7.4']

    name: PHP ${{ matrix.php-versions }} Test
    steps:
    - uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Validate composer.json
      run: composer validate

    #- name: Install dependencies
    #  run: composer install --prefer-dist --no-progress --no-suggest

    - name: Check syntax of sources
      run: composer run-script lint

    #- name: Run test suite
    #  run: composer run-script test

